services:
  nexus:
    container_name: bloblo_nexus
    image: sonatype/nexus3:3.72.0@sha256:c2c60fb29799b10e398615f6dcbf53f7e0a86650ee28f180585dacc3a7889a0d
    ports:
      - "8081:8081"
      - "8082:8082"
      - "6666:6666"
    volumes:
      - ./local_dev_configs/admin.password:/nexus-data/admin.password
      - ./local_dev_configs/nexus-default.properties:/opt/sonatype/nexus/etc/nexus-default.properties
      - ./local_storage/:/nexus-data/
    healthcheck:
      test: curl --fail http://127.0.0.1:8081 || exit 1
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 5s
  localstack:
    container_name: bloblo_localstack
    image: localstack/localstack:3.7.2@sha256:0595938dce1b36c488a52e6f04fbe805fb01f3b7e68ac2add02432d255954c79
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,secretsmanager
      - EAGER_SERVICE_LOADING=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"


